### PR TITLE
Colors: Add more!

### PR DESCRIPTION
**Pull request by jarstelfox**
Merge checklist
---

- [ ] Bump the package version by running `npm version [patch | minor | major]` from the command line (if applicable).

> **Note:** In the context of Core Primitives, significant changes to the library or workflow, or removing primitives would be considered a major update, adding or updating primitives would be considered a minor update, and fixing primitives would be considered a patch. Non-code changes (e.g. documentation) do not require a version bump.

qa_req 0

### CODE REVIEW

**Comment by ianrohde** [comment]
Hey Jarred - long time no talk!

Alpha's are probably overdue. I'm sure we'll use them 👍 

No issues with adding brand colors, but they should probably be named `ifixit` since they are specific to you guys.

We left the alternative gray families out intentionally. I was worried it would be confusing, and we could end up with random grays in use across the sites. IIRC we used the gray family that was the closest match to our existing. Thoughts?

**Comment by k0rvusk0r4x** [comment]
Is there a way for us to preview this? Are there more changes incoming before we do?

**Review by aburke07 — APPROVED** [review]
CR :alien:

**Comment by erinemay** [comment]
marking this qa req 0
deploy_block stands so we don't merge it and screw up things for Dozuki.

**Comment by jarstelfox** [comment]
un_deploy_block 🌵 Dozuki forked, so we can keep the name of brand (which matches the key in other repos)

**Pull request merged**
