### PR TITLE
Primitives: Fix LESS min breakpoint entries

### PR DESCRIPTION
**Pull request by ianrohde**
Summary of changes
---

`2.4.1` introduced a LESS bug with the newly minted `minBreakpoint` primitives. This PR fixes the issue by escaping only those entries in https://github.com/iFixit/core-primitives/commit/2a9a823aaa6782f76ff0e7a1f2697bccca23fd96

Now the result is:

```less
@min-breakpoint-sm: ~"@media (min-width: 576px)";
```

QA Notes
---

Screenshot of the built LESS file for confirmation:

CleanShot 2022-04-14 at 13 39 20@2x

Existing 2.4.1 primitives version (lines 234-237):
https://unpkg.com/browse/@core-ds/primitives@2.4.1/core-primitives.less

and the copy/pasta existing values to see the error highlight in my IDE:
CleanShot 2022-04-14 at 13 44 48@2x

Merge checklist
---

- [x] Bump the package version by running `npm version [patch | minor | major]` from the command line (if applicable).

> **Note:** In the context of Core Primitives, significant changes to the library or workflow, or removing primitives would be considered a major update, adding or updating primitives would be considered a minor update, and fixing primitives would be considered a patch. Non-code changes (e.g. documentation) do not require a version bump.

### CODE REVIEW

**Comment by ianrohde** [comment]
https://github.com/iFixit/core-primitives/pull/31/commits/a2f5f4e0758fdcf3d6d05bcffd07e0e1df444a11 should fix the duplicate version issue in https://github.com/iFixit/core-primitives/pull/31/commits/0c78795aa5da1e556b0452e44b4ced84b99aeb77 and https://github.com/iFixit/core-primitives/pull/31/commits/2240150377b253d446fe9982357691e4809678ca

**Review by andyg0808 — APPROVED** [review]

**Comment by andyg0808** [comment]
CR :goat: through a2f5f4e

**Comment by erinemay** [comment]
Talked to @ianrohde and the screenshots in the description are sufficient QA 🛩️. The error isn't occurring anymore with these changes and this shouldn't affect anything user-facing. 
> All other values stay the same

**Review by Michelle5102 — APPROVED** [review]
CR :octocat:

**Pull request merged**
