### PR TITLE
Primitives: Change fontSize to rem

### PR DESCRIPTION
**Pull request by probablyian**
Closes https://github.com/iFixit/ifixit/issues/56557

Summary of changes
---

[Convert fontSizes from px to rem](https://github.com/iFixit/core-primitives/commit/c3e6a24f5e359b3290a9cc73eab6ad9b9ffce547)

<details>
<summary>Details</summary>

- This is an accessibility improvement, allowing font size to adjust with zoomed pages
- rem values computed with a 14px base (Carpenter)
- NextJS has a 16px base, so we use Chakra's default fontSize scale there
- Once we use the same base font-size on both, we can update

</details>

Merge checklist
---

- [x] Bump the package version by running `npm version [patch | minor | major]` from the command line (if applicable).

> **Note:** In the context of Core Primitives, significant changes to the library or workflow, or removing primitives would be considered a major update, adding or updating primitives would be considered a minor update, and fixing primitives would be considered a patch. Non-code changes (e.g. documentation) do not require a version bump.

### CODE REVIEW

**Review by hcutrone — APPROVED** [review]
CR 🌯

**Comment by djmetzle** [comment]
Just noticed this is in the primitives repo. Do we need the same change in the monorepo?
https://github.com/iFixit/ifixit/blob/b5bac39c1638be4e369f0b54a27c0d8544cf2b9b/packages/primitives/index.json#L331-L344

**Comment by ianrohde** [comment]
> Just noticed this is in the primitives repo. Do we need the same change in the monorepo? [iFixit/ifixit@`b5bac39`/packages/primitives/index.json#L331-L344](https://github.com/iFixit/ifixit/blob/b5bac39c1638be4e369f0b54a27c0d8544cf2b9b/packages/primitives/index.json#L331-L344)

Oh yeah, good call out. Let me mull this over a bit before we proceed.

deploy_block 🔴

**Comment by ianrohde** [comment]
I considered taking over publishing the npm package from the mono, but it's a public package, so that's a no-go. I'll just set up our mono version in the workspace and stop using the npm package.

**Comment by ianrohde** [comment]
Handling these changes in the mono instead.

**Pull request closed without merging**
