### PR TITLE
core-primitives: correct font consts

### PR DESCRIPTION
**Pull request by ianrohde**
Summary of changes
---
Addresses typo @addison-grant spotted [here](https://github.com/iFixit/core-primitives/pull/13#discussion_r528304613)

QA
---
qa_req 0

Merge checklist
---

- [ ] Bump the package version by running `npm version [patch | minor | major]` from the command line (if applicable).

> **Note:** In the context of Core Primitives, significant changes to the library or workflow, or removing primitives would be considered a major update, adding or updating primitives would be considered a minor update, and fixing primitives would be considered a patch. Non-code changes (e.g. documentation) do not require a version bump.

### CODE REVIEW

**Comment by rjmccluskey** [comment]
CR 🍻

**Comment by danielbeardsley** [comment]
Are we using the old constant names somewhere?

It doesn't appear that we are in our main repo.

**Comment by ianrohde** [comment]
> Are we using the old constant names somewhere?

Not on our end. The change was introduced 25 days ago and only used if the package was updated.

**Comment by ardelato** [comment]
test

**Comment by addison-grant** [comment]
Mind if we mark this qa_req 0? Seems like it is just a small typo in something that is not used yet.

**Comment by addison-grant** [comment]
Quick question, should font settings and font face be added to the Primitives interface at the top?
https://github.com/iFixit/core-primitives/blob/9538402df71089abe336729fa7ca087eb35ce0ec/index.d.ts#L1-L10

I'm not quite sure what the Primitives interface does.

**Comment by addison-grant** [comment]
I wonder if it would be worth having an automated test that just tries to index into these properties. Could something like that catch small typos like those that this PR is solving?

**Comment by ianrohde** [comment]
Looks like they should be updated: https://www.typescriptlang.org/docs/handbook/interfaces.html

Cole set this up initally with a Github action, but they syntax has changed since then. It's on my list of things to address once other priorities are completed. These are updated very infrequently though, so I put it on the back-burner.

**Comment by addison-grant** [comment]
👍🏼 
un_deploy_block :sunny:

**Comment by rjmccluskey** [comment]
CR 🍻

**Comment by andrewjpiro** [comment]
CR :boom:

**Pull request merged**
